### ISSUE TITLE
Missing source book images

### ISSUE THREAD

**Issue by danny0838** [kanripo/KR3e0008#1]
An error message `No digital facsimile available for this text!SBCK 000-1a` is shown when viewing any book image at https://www.kanripo.org/edition/SBCK/KR3e0008/000, https://www.kanripo.org/edition/SBCK/KR3e0008/001, ...

**Comment by cwittern** [comment]
Yes indeed.  Most images from the SBCK are still missing, that is why you see this message telling you that there is no facsimile.

**Comment by danny0838** [comment]
@cwittern Could you add a check and disable the link if the corresponding source book image is not available?

**Comment by cwittern** [comment]
Hmm, when the page is generated it usually does not know this fact yet, that is why it is implemented like this. Have to think about it.
